apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-http-server
  namespace: ns-1
spec:
  selector:
    matchLabels:
      app: go-http-server
  template:
    metadata:
      labels:
        app: go-http-server
    spec:
      serviceAccountName: sa-1
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
        - name: go-http-server
          image: asia-southeast2-docker.pkg.dev/my-project-id/my-repo/go-http-server
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: go-http-server
  namespace: ns-1
spec:
  type: LoadBalancer
  selector:
    app: go-http-server
  ports:
    - port: 8080
      targetPort: 8080
