steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:latest",
        ".",
      ]
  # Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:latest",
      ]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:latest",
        "--region",
        "${_REGION}",
        "--allow-unauthenticated",
        "--service-account",
        "${_SERVICE_ACCOUNT}",
      ]
images:
  - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:latest
substitutions:
  # TODO: Supply _PROJECT_ID and _SERVICE_ACCOUNT through Cloud Build trigger or CLI command
  _IMAGE: chat-vertexai
  _REGION: asia-southeast2
  # TODO: Create a repository in Artifact Registry with the name below
  _REPOSITORY: cloud-projects
  _SERVICE_NAME: genai-chat-app
options:
  logging: CLOUD_LOGGING_ONLY
