version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: "/genai-chat-app"
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: "/game-of-life-v2"
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: "/news-grpc"
    schedule:
      interval: weekly

  - package-ecosystem: cargo
    directory: "/game-of-life-wasm"
    schedule:
      interval: weekly
