version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: "/game-of-life/with-vite"
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: "/game-of-life/with-wasm/www"
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: "/news-grpc"
    schedule:
      interval: weekly

  - package-ecosystem: cargo
    directory: "/game-of-life/with-wasm"
    schedule:
      interval: weekly
