name: Deploy GenAI Chat App
on:
  push:
    branches: [main]
    paths: ["genai-chat-app/**"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: "read"
  id-token: "write"

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SERVICE_ACCOUNT: ${{ secrets.GENAI_CHAT_APP_SA }}

jobs:
  deploy:
    name: Deploy GenAI Chat App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./genai-chat-app
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      # Authenticate to Google Cloud
      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: "${{ env.PROJECT_ID }}"

      - name: Deploy to Cloud Build
        run: gcloud beta builds submit --substitutions=_PROJECT_ID="${{ env.PROJECT_ID }}",_SERVICE_ACCOUNT="${{ env.SERVICE_ACCOUNT }}"
